# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-05 01:57
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20190802_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/7bnVFr7qWXu7x5DygPm8LcHJn8yMeLava9CnS6PgWQGv4gcatExUV6LAGPtvqvtT3revAfvj4tAG7t4c', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
