# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-30 06:54
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20190805_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/xGFstLpgUbx3jFLC7bfvVJlTY9w3wUBPaLsSVu38NYgYxGH9xVy4XFqBDPSaaYtqWrBWALh7bhcQksMp', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
