# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-06 06:14
from __future__ import unicode_literals

import deploy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20191030_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleattchment',
            name='attchment',
            field=models.FileField(blank=True, null=True, storage=deploy.storage.FileStorage(), upload_to='salt/module/c9sPqemNScLskSBJsjvrfypr3LdJk9CYRPjCMQ7NbGG6tNk5NEtUXx6LVXUc8wXQ8U5A5MwHaSaxMmXX', verbose_name='\u6a21\u5757\u4e0a\u4f20'),
        ),
    ]
